[tasks.llvm-cbe]
install_script = '''
mkdir -p llvm-cbe/build
cd llvm-cbe/build
cmake .. -DUSE_SYSTEM_LLVM=ON -DCMAKE_BUILD_TYPE=Release
make -j4
cd -
ln -sf llvm-cbe/build/tools/llvm-cbe/llvm-cbe ./llvm-cbe-bin
'''
